# Site settings
title: "Associação Reishin Kawai"
email: aikido@aikidorecife.org
phone: 

description: > # this means to ignore newlines until "baseurl:"
        Associação Reishin Kawai - Aikido Recife é um dojo de Aikido,
        localizado na cidade de Recife, em Pernambuco, Brasil.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aikidorecife.github.io" # the base hostname & protocol for your site

#twitter_username: jekyllrb
#github_username:  jekyll

facebook_group: https://www.facebook.com/groups/493629947331797/
gplus_group: https://plus.google.com/101194765953181339889/ 
youtube_group: https://www.youtube.com/user/PAULOCANDEA/videos
# Category-page generator
#category_dir : 
#category_title_prefix :

# Build settings
markdown: kramdown
